### ISSUE TITLE
provide flag for controlling log verbosity

### ISSUE THREAD

**Issue by mmguero** [cisagov/ICSNPP#14]
# 💡 Summary #

Some of the ICSNPP parsers can be very verbose (e.g., as far as individual values for writes/reads/operations vs. higher-level operations). It would be convenient to provide a flag to be able to control the verbosity of these logs per-protocol. In other words, a boolean where if set to "true" the verbosity is higher (i.e., more of the .log files are generated) vs. "false" where only summary logs are generated (not the details).

## Motivation and context ##

This idea came from the discussion we had with corelight.

## Implementation notes ##

An example of this could be the synchrophasor parser. See [main.zeek](https://github.com/cisagov/icsnpp-synchrophasor/blob/f03dcb6f95c3529a03a7e878ded2c4732f777494/analyzer/main.zeek#L17C1-L20).

**Comment by kkvarfordt** [comment]
Implemented and merged log policies to support Zeek log filtering.
