### ISSUE TITLE
Can't find Master branch or version tags

### ISSUE THREAD

**Issue by jdsmith21** [cisagov/ICSNPP#2]
# 🐛 Summary #

When using zkg to install any of the icnspp-* plugins i get a 'no "master" branch or version tags

## To reproduce ##

1. zkg install icsnpp-ethercat

## Expected behavior ##

installation of the plugin

## Any helpful log output or screenshots ##

Paste the results here:

```
 #zkg install icsnpp-ethercat
error: invalid package "icsnpp-ethercat": git repo has no "master" branch or version tags

# zkg install icsnpp-bacnet
error: invalid package "icsnpp-bacnet": git repo has no "master" branch or version tags
```

Add any screenshots of the problem here.

**Comment by Kleinspider** [comment]
We recently changed our default branch name from "master" to "main" so something may have gotten off sync with you zkg installation. Could you try doing a `zkg refresh` command and then try to install again? Another option would be to add `--version main` to the end of your install command (`zkg install icsnpp-ethercat --version main`). 

If neither of those options work would you mind sharing your version of zeek and zkg so we can work on reproducing this error and coming up with another fix?

**Comment by jdsmith21** [comment]
Adding "--version main" allowed us to install the packages.  We were also a bit behind on versions of zkg, and updated that as well.

Please consider this closed.
